affine_scale_loss_coeff: 800
atlas_resolution: 128
atlas_saliency_center_loss_coeff: 3000
atlas_saliency_loss_coeff: 5000
batch_size: 2
bootstrap_stn_sim: 1000
checkpoint_path: ''
data_folder: data/1image
dino_keys_layer: 11
dino_model_type: dino_vits8
dino_stride_size: 4
ext_gradual_atlas_training: false
ext_horizontal_flips: false
ext_update_flips_and_imgs_to_update_atlas_every: 100
flow_size: 128
global_rig_derivative: 20
global_rigidity_loss_coeff: 350
huber_delta_sal_loss: 0.7
image_resolution: 256
keys_output_cosine_loss_coeff: 4000
keys_output_loss_coeff: 3500
learning_rate_atlas: 0.0008
learning_rate_stn: 0.0001
local_rigidity_loss_coeff: 100
log_additional_vis_freq: 8000
log_images_freq: 1000
log_losses_freq: 50
log_to_wandb: false
mag_uv_loss_coeff: 8000
n_iters: 2001
pca_n_components: 5
pca_visualize_with_global_minmax: false
real_size: 256
results_folder: results/2024-10-02_19-29-43_1image
save_complete_state: true
save_model_freq: 1000
save_model_initialization: false
save_model_starting_epoch: 7000
seed: 4180764158
sparsity_l0_loss_saliency_coeff: 0.5
sparsity_l1_loss_saliency_coeff: 1
sparsity_loss_keys_coeff: 10
sparsity_loss_saliency_coeff: 450
stn_channel_multiplier: 0.5
stn_head_antialias: false
stn_padding_mode_im: border
stn_padding_mode_keys: border
stn_padding_mode_saliency: zeros
upload_trained_model_checkpoint: false
use_griddata: false
use_masks: true
wandb_entity: wandb_entity_name
wandb_project: wandb_project_name
